### PR TITLE
Add next boilerplate, skeleton of pages/components

### PR DESCRIPTION
**Pull request by srslie**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [x] Adds a new feature
- [ ] Improves an existing feature
- [ ] Fixes a bug
- [ ] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*
Adds skeleton of next.js app pages and components
Created cypress & context file structure
Added CircleCi configuration

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have run Lighthouse/Wave checks for accessibility
- [ ] New and existing unit tests pass locally with my change

### CODE REVIEW

**Review by alia-peterson — APPROVED** [review]
- [x] Changes generate no new warnings or errors
- [x] Branch was tested locally without failures
- [ ] All tests are passing as expected

**Review by lbmerchant93 — APPROVED** [review]
Looks great to me, set up looks correct and now with the boilerplate we can all start dividing up the work on each of the components laid out and assigned on the project board. If creating more components or pages remember that pages don't start with a capital but components do

**Review by camaragon — COMMENTED** [review]
This is a great start to getting the frontend setup. Great job figuring out the cypress problem and installing it correctly. Now we can all start our individual issues after the context and CI is setup.

**Review by camaragon — APPROVED** [review]
I approve these changes

**Comment by camaragon** [comment]
Deployed to Vercel

**Pull request merged**
